# Generated by Django 3.1.5 on 2021-04-03 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210403_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('select_repeat_type', models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=200, null=True)),
                ('select_shift_type', models.CharField(choices=[('Morning Shift - 5am t0 9am', 'Morning Shift - 5am t0 9am')], max_length=200, null=True)),
                ('select_start_time', models.TimeField()),
                ('select_end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
