# Generated by Django 3.1.5 on 2021-04-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_shift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('user', 'start_date', 'select_repeat_type')},
        ),
    ]
